version: '3.6'

services:

  settings-tp:
    build:
      context: ./sawtooth-core/ci/nightly
      dockerfile: sawtooth-settings-tp
    # image: hyperledger/sawtooth-settings-tp:nightly
    container_name: settings-tp
    depends_on:
      - validator
    command: |
      bash -c "
        settings-tp -vv -C tcp://validator:4004
      "
    stop_signal: SIGKILL

  # intkey-tp-python:
  #   build:
  #     context: ./sawtooth-sdk-python/ci/nightly
  #     dockerfile: sawtooth-intkey-tp-python
  #   # image: hyperledger/sawtooth-intkey-tp-python:nightly
  #   container_name: intkey-tp-python
  #   expose:
  #     - 4004
  #   depends_on:
  #     - validator
  #   command: |
  #     bash -c "
  #       intkey-tp-python -vv -C tcp://validator:4004
  #     "
  #   stop_signal: SIGKILL


  # xo-tp-python:
  #   build:
  #     context: ./sawtooth-sdk-python
  #     # dockerfile: ./examples/xo_python/my-build
  #     dockerfile: ./examples/xo_python/Dockerfile-installed-bionic
  #     # context: ./sawtooth-sdk-python/ci/nightly
  #     # dockerfile: sawtooth-xo-tp-python
  #   # image: hyperledger/sawtooth-xo-tp-python:nightly
  #   container_name: xo-tp-python
  #   depends_on:
  #     - validator
  #   command: |
  #     bash -c "
  #       xo-tp-python -vv -C tcp://validator:4004
  #     "
  #   stop_signal: SIGKILL


  client:
    build:
      context: ./sawtooth-core/ci/nightly
      dockerfile: sawtooth-shell
    # image: hyperledger/sawtooth-shell:nightly
    container_name: sawtooth-shell
    depends_on:
      - validator
    command: |
      bash -c "
        sawtooth keygen &&
        tail -f /dev/null
      "
    stop_signal: SIGKILL


  validator:
    build:
      context: ./sawtooth-core/
      dockerfile: validator/Dockerfile-installed-bionic
    # image: hyperledger/sawtooth-validator-local:nightly
    container_name: validator
    expose:
      - 4004
      - 8800
      - 5050
    ports:
      - "4004:4004"
    # start the validator with an empty genesis batch
    command: |
      bash -c "
        sawadm keygen
        sawset genesis \
          -k /etc/sawtooth/keys/validator.priv \
          -o config-genesis.batch && \
        sawset proposal create \
          -k /etc/sawtooth/keys/validator.priv \
          sawtooth.consensus.algorithm.name=Devmode \
          sawtooth.consensus.algorithm.version=0.1 \
          -o config.batch && \
        sawadm genesis config-genesis.batch config.batch && \
        sawtooth-validator -vv \
            --endpoint tcp://validator:8800 \
            --bind component:tcp://eth0:4004 \
            --bind network:tcp://eth0:8800 \
            --bind consensus:tcp://eth0:5050 \
      "
    stop_signal: SIGKILL


  rest-api:
    build:
      context: ./sawtooth-core/ci/nightly
      dockerfile: sawtooth-rest-api
    # image: hyperledger/sawtooth-rest-api:nightly
    container_name: rest-api
    ports:
      - "8008:8008"
    depends_on:
      - validator
    command: |
      bash -c "
        sawtooth-rest-api -v --connect tcp://validator:4004 --bind rest-api:8008
      "
    stop_signal: SIGKILL


  devmode-rust:
    image: hyperledger/sawtooth-devmode-engine-rust:nightly
    container_name: devmode-engine-rust
    depends_on:
      - validator
    command: |
        devmode-engine-rust -v --connect tcp://validator:5050
    stop_signal: SIGKILL
